dist: xenial
language: generic
notifications:
  email: false
cache:
  directories:
    - $HOME/.stack
addons:
  apt:
    packages:
      - libgmp-dev
before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
  - stack --no-terminal --install-ghc test --only-dependencies
  - stack install stack-hpc-coveralls
script:
  - stack --no-terminal test --coverage
after_script:
  - shc haskell-book haskell-book-test
