language: haskell
ghc: 8.6.5
notifications:
  email: false
script:
  - cabal configure --enable-tests --enable-library-coverage && cabal build && cabal test
after_script:
  - cabal install codecov-haskell
  - codecov-haskell haskell-book-test
