language: haskell
ghc: 8.6.5
notifications:
  email: false
script:
  - cabal configure --enable-tests --enable-library-coverage && cabal build && cabal test
after_script:
  - cabal sandbox init && cabal install codecov-haskell
  - .cabal-sandbox/bin/codecov-haskell --display-report haskell-book-test

