version: 2.1
orbs:
  haskell: haskell-works/haskell-build-2@1.6.8
workflows:
  build:
    jobs:
      - haskell/build:
          name: GHC 8.6.3
          executor: haskell/ghc-8_6_3
          cache-version: latest
          run-check: false
          before-build:
            - run: cabal configure --enable-tests --enable-library-coverage && cabal build && cabal test && cabal install codecov-haskell && codecov-haskell --display-report haskell-book-test
