version: 2.1
orbs:
  haskell: haskell-works/haskell-build-2@1.6.8
workflows:
  build-my-application:
    jobs:
      - haskell/build:
          before-build:
            - run: cabal configure --enable-tests --enable-library-coverage
          after-build:
            - run: cabal build && cabal test
          before-test:
            - run: cabal install codecov-haskell
          after-test:
            - run: codecov-haskell --display-report haskell-book-test
