version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - haskell-book-v1-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
            - haskell-book-v1-{{ checksum "stack.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack --no-terminal setup
      - run:
          name: Run tests
          command: stack --no-terminal test --coverage
      - codecov/upload:
          file: /root/project/.stack-work/install/x86_64-linux/f5b7af260f8222e07e6c42b8b8deba8927651e70b99955dcf610cadc5328f339/8.6.5/hpc/index.html
      - save_cache:
          name: Cache Dependencies
          key: haskell-book-v1-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
