version: 2.1
orbs:
  haskell: haskell-works/haskell-build-2@1.6.8
workflows:
  build-my-application:
    jobs:
      - haskell/build:
          run-check: false
          before-build:
            - run: |
              cabal configure --enable-tests --enable-library-coverage
              cabal new-install cabal-cache
          after-build:
            - run: cabal build && cabal test
          after-test:
            - run: cabal install codecov-haskell && codecov-haskell --display-report haskell-book-test
