version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - haskell-book-v1-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
            - haskell-book-v1-{{ checksum "stack.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack --no-terminal setup
      - run:
          name: Run tests
          command: stack --no-terminal test --coverage
      - run:
          name: Send coverage
          command: |
            stack install stack-hpc-coveralls
            shc haskell-book haskell-book-test
      - run:
          name: Install executable
          command: stack --no-terminal install
      - save_cache:
          name: Cache Dependencies
          key: haskell-book-v1-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
      - store_artifacts:
          path: ~/.local/bin/haskell-book-exe
          destination: haskell-book-exe

