version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - haskell-book-v1-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
            - haskell-book-v1-{{ checksum "stack.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack --no-terminal setup
      # - run:
      #     name: Run tests
      #     command: stack --no-terminal test --coverage
      - run:
          name: Send coverage
          command: |
            cabal install codecov-haskell
            cabal configure --enable-tests --enable-library-coverage && cabal build
            run-cabal-test # [options] [cabal-test-options]
            codecov-haskell --display-report haskell-book-test
      - codecov/upload:
          file: $(find $(stack path --local-hpc-root) -name \*.xml)
      - save_cache:
          name: Cache Dependencies
          key: haskell-book-v1-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
