version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - haskell-book-v1-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
            - haskell-book-v1-{{ checksum "stack.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack --no-terminal setup
      - run:
          name: Run Tests and Report Coverage!
          command: |
            stack --no-terminal --install-ghc test --only-dependencies --silent
            stack install stack-hpc-coveralls
            stack --no-terminal test --coverage
            codecov-haskell --display-report haskell-book-test
      - save_cache:
          name: Cache Dependencies
          key: haskell-book-v1-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
