version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          name: Restore Cached Dependencies
          keys:
            - haskell-book-v1-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
            - haskell-book-v1-{{ checksum "stack.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack --no-terminal setup
      - run:
          name: Install Coveralls.io for Haskell
          command: stack --no-terminal install stack-hpc-coveralls
      - run:
          name: Run tests
          command: stack --no-terminal test --coverage --silent
      - store_artifacts:
          path: coverage
      - run:
          name: Report coverage
          command: shc haskell-book haskell-book-test
      - run:
          name: Install executable
          command: stack --no-terminal install
      - store_artifacts:
          path: ~/.local/bin/haskell-book
          destination: haskell-book
      - save_cache:
          name: Cache Dependencies
          key: haskell-book-v1-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
