name: Haskell CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.6.5'
        cabal-version: '3.0'
    - name: Install dependencies
      run: |
        sudo apt-get install libcurl4-openssl-dev # github needs this...
        cabal update
        cabal configure --enable-tests --enable-coverage --only-dependencies
    - name: Build
      run: cabal build
    - name: Run tests
      run: cabal test
    - name: Send coverage
      run: |
        cabal install codecov-haskell --installdir=/opt/cabal/3.0/bin/
        find . -type f -name "*.tix" # where is my tix file??
        # codecov-haskell --display-report haskell-book-test
