name: Haskell CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.6.5'
        cabal-version: '3.0'
    - name: Install dependencies
      run: |
        cabal update
        cabal install --only-dependencies
    - name: Build
      run: |
        cabal configure --enable-tests --enable-library-coverage
        cabal build
    - name: Run tests
      run: cabal test
    - name: Send coverage
      run: |
        sudo apt-get install curl libcurl libcurl-dev
        cabal install codecov-haskell
        codecov-haskell --display-report haskell-book-test
    - uses: codecov/codecov-action@v1.0.3
      with:
        token: ${{secrets.CODECOV_TOKEN}}
    #     file: ${find dist-newstyle -name hpc_index.html -print -quit}
