name: Haskell CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.6.5'
        cabal-version: '2.4'
    - name: Install dependencies
      run: |
        sudo apt-get install libcurl4-openssl-dev # github needs this...
        cabal update
        cabal new-install --only-dependencies
        cabal new-install codecov-haskell --installdir=/home/runner/.cabal/bin
    - name: Build
      run: cabal new-build --only-dependencies --enable-tests --enable-coverage
    - name: Run tests
      run: run-cabal-test
    - name: Send coverage
      run: codecov-haskell --display-report haskell-book-test
