name: Haskell CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v6
    - uses: cachix/cachix-action@v3
      with:
        name: kutyel
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    # TODO: send coverage
    # - name: Send coverage
    #   run: |
    #     stack install stack-hpc-coveralls
    #     shc haskell-book haskell-book-test
