name: Haskell CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v8
        with:
          name: kutyel
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
      - run: nix-build
      - name: Setup stack & Send coverage
        uses: mstksg/setup-stack@v2
        run: |
          stack install stack-hpc-coveralls
          shc haskell-book haskell-book-test
