name: Haskell CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v8
        with:
          name: kutyel
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
      - run: nix-build
      - uses: actions/setup-haskell@v1.1
        with:
          ghc-version: "8.8.3" # Exact version of ghc to use
          enable-stack: true
          stack-version: "latest"
      - name: Send coverage
        run: |
          stack install stack-hpc-coveralls
          shc haskell-book haskell-book-test
